<?php

namespace pruebaBundle\Repository;

/**
 * EjemploRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EjemploRepository extends \Doctrine\ORM\EntityRepository
{
}
