<?php

namespace pruebaBundle\Repository;

/**
 * libreriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class libreriaRepository extends \Doctrine\ORM\EntityRepository
{
}
